MONTH := "12"

; Add FMS formatted carriers & agents to locate correct carrier/agent (e.g. COSCO HOUSTON (A/P))
CarrierArray := {APL: "APLU", ONE: "ONEY", CMA: "CMDU", MAERSK: "MAEU", COSCO: "COSU", MSC: "MEDU", HAPAG: "HLCU", OOCL: "OOLU", SMLINE: "SMLM", YANGMINGLINE: "YMLM"}

PDQDArray := {AGENTREF: "PDQDJM", FMSAGENT: "PUDONG TRANS (QD)", LOADPORT: "57047", CARRIERS: {APL: {MBL: "APLU", AGENTREF: "PDQDJMQJ"}, ONE: {MBL: "ONEYTA8PK0", AGENTREF: "PDQDJMON"}, CMA: {MBL: "CMDUQDJY", AGENTREF: "PDQDJMCM"}, MSC: {MBL: "MEDUQ", AGENTREF: "PDQDJMMS"}, MAERSK: {MBL: "MAEU", AGENTREF: "PDQDJMMK"}, COSCO: {MBL: "COSU619", AGENTREF: "PDQDJMCO"}, HAPAG: { MBL: "HLCUTA" . MONTH . "8", AGENTREF: "PDQDJMQQ"}, ZIM: {MBL: "ZIMUQIN", AGENTREF: "PDQDJMBS"}}}

PDTJArray := {AGENTREF: "PDTJJ", FMSAGENT: "NEPTUNE (QD)", LOADPORT: "57017", CARRIERS: {APL: {MBL: "APLU", AGENTREF: "PDTJJMAP"}, ONE: {MBL: "ONEYTS8NN0", AGENTREF: "PDTJJMON"}, CMA: {MBL: "CMDUCNSE", AGENTREF: "PDTJJMCM"}, MAERSK: {MBL: "MAEU", AGENTREF: "PDTJJMMK"}, COSCO: {MBL: "COSU619", AGENTREF: "PDTJJMCO"}, MSC: {MBL: "MEDUQ", AGENTREF: "PDTJJMMS"}, HAPAG: {MBL: "HLCUTS", AGENTREF: "PDTJJMHP"}, SMLINE: {MBL: "SMLMTSPM", AGENTREF: "PDTJJMSM"}}}

AgentsFuncArray := {PDQD: PDQDArray, PDTJ: PDTJArray}

LoadPortArray := {57047: "QDF", 57035: "SHF", 57069: "XMF", 57078: "YTF", 57043: "TJF", 57017: "TJF", 57081: "LGF", 57051: "DLF"}